global_variables:
  max_tokens: 8192
  temperature: 0.5
  model_name: "Qwen2.5-7B"
  xml_version: "1.0"
  timestamp: "{timestamp}"

categories:
  agents:
    variables:
      context: ""
      filename: ""
      request: ""
      task_type: ""
      schema_path: ""
      id_prefix: ""
  tools:
    variables:
      tool_name: ""
      arguments: ""
      description: ""
      operation: ""
      action: ""
  system:
    variables:
      error_type: ""
      error_message: ""
      retry_count: ""
      format_instructions: ""
      tool_definitions: ""